- commands.py
- memebot.py
**Does this improvement fix a bug/issue? Please describe.**
N/A
**What do you dislike about the feature in its current state?**
The issue is that the `Command` class isn't set up to really handle more than text being returned. It should be able to send back data that can instantly be sent off to discord without further processing.
**Describe the solution you'd like**
Format all command functions to return a dictionary that specifies the data being sent as keyword arguments to the `send` command. This way, the dictionary can simply be used as `**data` when it is sent. This also allows the `Command` methods to return multiple pieces of data through one object.
**What tradeoffs are made by implementing your improvement?**
The functions in the `Command` class become a little more complicated, …
> Improve Commands class to fully handle data that is sent to Discord

- commands.py
- memebot.py
My thought process here is that hardcoding strings multiple times makes my skin crawl, and it also makes programmers less reliant on the documentation to determine what data they're allowed to send in a discord message. If you like it, cool.
> Create CommandOutput class so dicts/strings don't have to be hardcoded

- README.md
- commands.py
- main.py
- memebot.py
Resolves #5 
Subcommands `create`, `join`, `leave`, `delete`, `list`. `Delete` will only delete a memberless role. `List` will list members of a role. Users can join a role that they are already in and leave a role that they are already not in with no unerlying effect. 
Added temporary workaround to give all fucntions in `Commands` class access to the message object on which they are acting (`Commands.command_message`). This is protected by a global lock for now. 
Refactored some code to allow for `async` function calls within the `Commands` functions. This required making every `Commands` funciton `async` and adding a few `await` statements.
> Role Moderation

- Dockerfile
- README.md
- main.py
This PR adds the ability to deploy Memebot with Docker. A Dockerfile was added at the root of the repository, with some supplimentary information in the README. A line in [main.py](./main.py) was also amended to reflect an apparent change with file.read() in python 3.8, wherein a newline is placed at the end of the string, even if it doesn't exist in the file. This newline causes authentication to Discord to fail. Mitigating this is as simple as "stripping" the file of whitespace.
I would like at least one reviewer to test the Docker image on their machine. It is fairly straightforward:
1. Install Docker
2. cd into the repository root
3. Build the Docker image with `docker build -t memebot .`
4. Run the container with `docker run --rm -d --name memebot-test memebot`
5. Test the container …
> Add Docker support

- commands.py
Using the command '!role list' with no role argument will list all the 
roles that can be managed by memebot.
The bot can manage all roles below its highest role in the hierarchy.
> Add role list command with no argument

- memebot.py
Our parsing did not recognize curly quotes as quotes, and would fail to parse
commands which used them. Replacing all curly quotes in the message with
straight quotes before parsing solves this problem.
> Replace curly quotes with straight quotes

- commands.py
Ensures that role names and subcommands are not case-sensitive.
> Process !role arguments as lower-case

- src/commands/commands.py
Roles with the same name as the bot are automatically generated and used
to manage the bot. This isn't considered a role that can be managed by the bot,
so exclude it from the list.
> Exclude listing roles with same name as bot

- src/commands/commands.py
supplying a command such as `!role ?` would return a failure message that was malformed due to the missing third argument. Now, catch this ahead of time and return a help message when the action is not among the known actions.
> Better handle malformed role commands

- src/memebot.py
Adding privileges intents is now required for accessing members. Without
privileged intents, the author is None and the bot crashes.
This change also requires a change in the bot to give it access to privileged
intents. This should be done in the dev portal.
Fixes #51
> Add all intents to bot

- src/commands/__init__.py
- src/commands/command.py
- src/commands/help/__init__.py
- src/commands/registry.py
- src/commands/role/__init__.py
- src/commands/role/create.py
- src/commands/role/delete.py
- src/commands/role/join.py
- src/commands/role/leave.py
- src/commands/role/list.py
**Does this improvement fix a bug/issue? Please describe.**
N/A
**What do you dislike about the feature in its current state?**
Commands have to be manually registered in the constructor, which is inconvenient and unnecessary work for the command implementer.
**Describe the solution you'd like**
Dynamically load the the individual command modules when the `command` module loads, i.e. in `commands/__init__.py`. There is currently a placeholder function where this should take place.
**What tradeoffs are made by implementing your improvement?**
Adds a minor layer of complexity to command infrastructure, but is unlikely to need changes unless a command with wildly different format is created.
**Describe alternatives you've considered**
Manually adding commands is not a terrible solution, and …
> Commands module should automatically load commands

- src/commands/__init__.py
I am not sure how this functionality ever worked tbh.
The latest commit on master as of right now does not register any subcommands.
Subcommand registration is now done top-down, using a recursive depth-first search. If you can think of a way to do it iteratively, please comment.
> Fix subcommand registration

- src/commands/command.py
- src/commands/command_output.py
- src/commands/execution.py
- src/commands/role/__init__.py
- src/lib/status.py
**Description**
If a Command fails for whatever reason, there is nothing to communicate the outcome of the command and the callback is called regardless.
**To Reproduce**
1. Run `!poll`
2. Observe that the callback runs even though the command fails gracefully
**Expected behavior**
On command failure, the callback should be skipped. 
**Additional context**
We could maybe optionally allow a callback to run if commands fail under certain circumstances, but I can't imagine a scenario where regular cleanup in `Command.exec` would not suffice.
> Command callbacks are called regardless of whether or not command fails

- src/commands/role/__init__.py
- src/commands/role/join.py
Now, when a user joins a role they are already a member of, a proper
error message is sent instead of a duplicate success message.
fixes #49
> Fix role double-join errors

- README.md
- src/config/__init__.py
- src/main.py
- src/memebot.py
Memebot now has the framework for manual reconfig through command-line parameters. Currently, the only two supported options are:
```
--discord-api-token
--twitter-api-tokens
```
In the future, being able to add command-line parameters will make testing and configuring the bot much easier.
> Support config through command-line parameters

- requirements.txt
- src/memebot.py
The python-twitter package is fully replaced by Tweepy, plus a few minor optimizations:
1. The tweet-checking regex now runs against the entire message, instead of once per word. The Twitter URL is then extracted via group matching.
2. Some functions have been renamed to be more clear.
3. Extracted quote tweet URLs now follow the `twitter.com/user/status/1234` format instead of `twitter.com/i/web/1234`.
4. API access is now by default read-only.
This patch was fairly painless, as tweepy happens to be reasonably similar to python-twitter.
Fixes #63.
> Migrate Twitter integration to tweepy

- src/main.py
- src/memebot.py
Cleaned up a small bit of `MemeBot` code to make it so that the `MemeBot` constructor does not populate the global variable `memebot.client`, and that variable is instead populated at module-load time. This way, it is never null, and we can ensure that everyone is accessing the same `MemeBot` object (as best we can without a `const` qualifier, anyway.)
> Make `memebot.client` non-nullable

- src/commands/help/__init__.py
This change sorts the commands by name when `!help` is called. 
It will also evenly space the commands.
> Alphabetize output of !help

- src/commands/role/__init__.py
- src/commands/role/create.py
- src/commands/role/delete.py
- src/commands/role/join.py
- src/commands/role/leave.py
- src/commands/role/list.py
Previously, the `!role` command would only allow users to input the name of a role, and would error if the user attempted to @ the role. This was inconvenient, because a lot of users use @ mentions for their autocomplete. Now, users can choose to @ the role with which they want to interact, or not! Either will work :)
Also, refactored any uses of `target_name` variables after a `discord.Role` object would have been resolved, so that the name of the role output to the user will always be canonical, and not a long integer ID if it was an @ mention.
Resolves #56.
> Allow `!role` command to be used with @ mentions

- src/commands/role/leave.py
Used to be that a feller could come round here and leave a role he warn't even
in. Nowadays we don't like that around here.
> Fix double-leave bug

- src/memebot.py
The main `on_message()` logic used to `return` immediately when the message was from Memebot itself. Now, it will do all the logic except for executing a command, because we still don't want the bot running commands sent by itself. 
Also, `re.match()` matches only from the beginning of the string, which leads to undesirable behavior in some circumstances (e.g. multiline message with tweet on line 2). Instead, I changed it to use `re.search()`, which scans the whole string for a regex match. 
Fixes #70
> Make memebot react to itself + fix twitter regex

- docker/docker-compose.yaml
Explicitly sets the containers' DNS servers as the Docker network's router, which will forward to the local relay. For some reason, not specifying this would drastically slow down DNS lookups even though the DNS server would still resolve to the same device.
> Fix container DNS speed issues

- README.md
- src/config/__init__.py
- src/integrations/twitter.py
- src/memebot.py
All of MemeBot's Twitter integration has been moved to a [separate module](src/integrations/twitter.py), and have been made asynchronous and stateless. The only state managed by the Twitter module is whether or not MemeBot has authenticated to the Twitter API. This is done by MemeBot using the `twitter.init` function. If MemeBot attempts to make any API calls before `init` is called, the functions which make those calls will throw.
Fixes #64.
> Move Twitter integration to separate module

- README.md
- src/config/__init__.py
- src/config/validators.py
- src/log/__init__.py
- src/log/formatter.py
- src/log/logger.py
- src/main.py
- src/memebot.py
I have created a basic logging system for MemeBot based on python's own `logging` package. I have set up a custom formatter and all external modules will use it. We also redirect stdout to a MemeBot logger so any external libraries using print will be formatted as well. Any print statements used from within MemeBot will be logged at the INFO level, where any calls not written by us will be logged as DEBUG. This was done so that we can use print debugging without having to raise the log level.
As of right now, logging has not been fully integrated into the codebase. This patch was already pretty large, and I figured it would be better to have the foundation of the logging system merged before more logging statements were added.
> Create logging subsystem

- src/log/logger.py
Swapped our use of `functools.cache` to `functools.lru_cache`. I was led to believe that using the `cache` wrapper would be fine because it was implemented in python 3.8, but for some reason it doesn't exist in the Docker image.
> Use `functools.lru_cache` instead of `functools.cache`

- src/commands/command.py
- src/commands/hello/__init__.py
- src/commands/help/__init__.py
- src/commands/poll/__init__.py
- src/commands/role/__init__.py
- src/commands/role/create.py
- src/commands/role/delete.py
- src/commands/role/join.py
- src/commands/role/leave.py
- src/commands/role/list.py
The `!help` command will now print longer descriptions and usage instructions for other commands when given their name as an argument. For example:
> !help hello
> A simple ping command. Memebot should respond "Hello!"
>
> **`!hello`**
> !help role list
> List all roles managed by Memebot, or provide the name of a role and list all members of that role.
>
> **`!role list [role]`**
The refactors to the [`Help`](src/commands/help/__init__.py) class were pretty minor, and only include checking for arguments, finding a command that matches the arguments, and printing that command's help text. The behavior for usage with no arguments remains the same.
Several refactors were made to the [`Command`](src/commands/command.py) class to allow it to have more nuanced behavior with regard to helping …
> Extend `!help` command to accept names of other commands as arguments

- src/integrations/twitter.py
Since Discord removed twitter video embeds, we will post the raw video link in chat so that people can watch the video without leaving Discord. We determine it is a video by looking for the 'video_info' attribute in its media info dict. The API doesn't flag videos differently in any way, so this was the best solution I could come up with. We then search through all of its variants for the highest bitrate, and post the link to that variant.
> Post videos in chat when a Tweet has a video

- src/log/logger.py
Python is unable to inspect the stack in the interactive repl, so I fixed a bug that would cause the logger to throw every time it attempted to intercept a print statement. The logger will now detect when it is in interactive mode and write the message directly to the true stdout.
> Fix logging in interactive mode

- src/commands/role.py
Previously we used the built in argument converter for `discord.Role`. That converter is case-sensitive though, so I wrote a thin wrapper around it to always use the `.lower()` of the role name. 
To get around some type checker complains regarding the function annotation, I had to use `cast()` (and changed the name of the function argument to keep the diff clean). Once we update to discord.py 2.0 (#117), we can remove the `cast`s and use [`typing.Annotated`](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html?highlight=annotated#typing-annotated) (technically a part of #119)
fixes #125
> Convert role arguments to lowercase

- .github/dependabot.yaml
Workflows can fall out of date, and shouldn't affect code correctness on updates, so Dependabot will manage updates. Pip packages are not watched because there are no tests yet, and those upgrades could easily break code. As such, this patch only solves a piece of #93.
> Use Dependabot to update GitHub Actions

- .github/workflows/docker.yaml
Using a pinned version of cosign has caused the Docker workflow to fall out of date and fail to sign the image. Rather than have this periodically happen, we will use the latest version available by simply not specifying a version.
> Use latest version of cosign available for Docker workflow

- src/commands/role.py
By running `!role list <username>`, you can now list the MemeBot-managed roles for a given user. The argument to `!role list` can now be either a role or a user, so if there is a user and a role with the same name, the role will take priority when parsing and converting the arguments.
> Add ability to list roles by user

- requirements.txt
- src/commands/help.py
- src/commands/poll.py
- src/commands/role.py
- src/memebot.py
After upgrading the requirements and testing, i found that everything worked. The only thing that needed to be changed was our usage of the [`clean_prefix` property](https://discordpy.readthedocs.io/en/stable/migrating.html#id2) in the code for the help command. 
Version 2.0+ is fully typed, so the stubs are no longer needed and can be removed from the requirements.
> Upgrade to discord.py 2.1.0

- src/commands/role.py
The message used to claim the command was called `!list`, but now it properly uses the parent command's name.
> Fix message for `!role list` commands

- src/commands/role.py
Before this, it was not possible to annotate command arguments with with their type while also using an argument converter. Now in 2.0+, discord.py supports using `typing.Annotated` to annotate an arguments type and provide a custom converter.
https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#typing-annotated
Part of #119
> Properly annotate role subcommand arguments

- src/integrations/twitter.py
At some point, Twitter started including x-mpeg playlist files in their media lists, which do not resolve to videos. This resulted in bad embed links being posted by Memebot. Now, we filter the media by videos only to ensure we select a good video link to post.
> Use valid video files in Twitter embeds

- src/commands/poll.py
Instead of using reactions for the poll command, we can instead use interaction buttons. This also allows us to dynamically update the poll embed with the names of who voted.
> Add interactions to poll command

- docker/Dockerfile
This had previously been done in our Dockerfile but was reintroduced by b81f11823c34bc59460918544cf5072304f7a785
> Clean apt lists after install dependencies in Dockerfile

- memebot/commands/role.py
- tests/commands/test_role.py
Before this, the role list would be publicly viewable, which isn't too useful in general and has a tendnecy to fill the chat with noise. In practice, only the user invoking the command cares about the result.
> Make role list outputs ephemeral

- tests/requirements.txt
Includes a dependency on `black` for test builds. Added convenience for those who prefer to use a bundled package rather than a system package
> Add black dependency to test build

- memebot/log/__init__.py
- memebot/log/filter.py
- memebot/log/formatter.py
- memebot/log/logger.py
The logger now behaves as desired, relying more on logging internals and stable APIs to resolve the information it requires for formatting.
* Insert fully qualified module path via a new log filter instead of unstable `_log` override
* Remove complicated caller-resolution code
* Allow logging internals to resolve calling code by pushing up the base stack frame in log helpers
* Simplify existing formatting code
Resolves #290
> Simplify global logger
